version: '3'

services:
  postgres:
    # container_name: db
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    ports:
      - '5432:5432'
  mailserver:
    image: namshi/smtp
    ports:
      - '25:25'    # SMTP  (explicit TLS => STARTTLS)
      - '143:143'  # IMAP4 (explicit TLS => STARTTLS)
      - '465:465'  # ESMTP (implicit TLS)
      - '587:587'  # ESMTP (explicit TLS => STARTTLS)
      - '993:993'  # IMAP4 (implicit TLS)

volumes:
  pgdata:
