version: '3'
services:
    postgres:
        container_name: lsalab-postgres-1
        image: postgres
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: strapi
            POSTGRES_PASSWORD: strapi
            POSTGRES_DB: strapi
        ports:
            - '127.0.0.1:5435:5432'
    postgres-test:
        container_name: lsalab-postgres-test-1
        image: postgres
        restart: always
        volumes:
            - pgdata-test:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: strapi
            POSTGRES_PASSWORD: strapi
            POSTGRES_DB: strapi
        ports:
            - '127.0.0.1:5433:5432'

volumes:
    pgdata:
    pgdata-test:
