name: 'Tests'

on:
    push:
        branches: main
    pull_request:

jobs:
    lint:
        name: 'lint (node: ${{ matrix.node }})'
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [12, 14, 16]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: ${{ matrix.node }}
    unit_back:
        name: 'unit_back (node: ${{ matrix.node }})'
        needs: [lint]
        runs-on: ubuntu-latest
        # env:
        #     CODECOV_TOKEN: ${{ secrets.codecov }}
        strategy:
            matrix:
                node: [12, 14, 16]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: ${{ matrix.node }}
            # - uses: ./.github/actions/install-modules
            #   with:
            #       globalPackages: codecov
            - name: Run tests
              run: yarn run -s test:back --coverage

    unit_front:
        name: 'unit_front (node: ${{ matrix.node }})'
        needs: [lint]
        runs-on: ubuntu-latest
        # env:
        #     CODECOV_TOKEN: ${{ secrets.codecov }}
        strategy:
            matrix:
                node: [12, 14, 16]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: ${{ matrix.node }}
            # - uses: ./.github/actions/install-modules
            #   with:
            #       globalPackages: codecov
            - name: Build
              run: yarn build:front
            - name: Run test
              run: yarn run -s test:front
